# Generated by Django 3.2.4 on 2021-06-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0005_auto_20210627_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_daily',
            old_name='code',
            new_name='ts_code',
        ),
        migrations.AddField(
            model_name='stock_basic',
            name='ts_code',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AddField(
            model_name='stock_daily',
            name='amount',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='stock_daily',
            name='change',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='stock_basic',
            name='code',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='stock_daily',
            unique_together={('date', 'ts_code')},
        ),
        migrations.AlterIndexTogether(
            name='stock_daily',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='stock_daily',
            name='name',
        ),
    ]
