# Generated by Django 3.2.4 on 2021-12-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0006_auto_20210630_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(default='', max_length=100)),
                ('trade_date', models.CharField(default='', max_length=20)),
                ('open', models.FloatField(default=None)),
                ('high', models.FloatField(default=None)),
                ('low', models.FloatField(default=None)),
                ('close', models.FloatField(default=None)),
                ('updatetime', models.CharField(default='', max_length=100)),
            ],
            options={
                'unique_together': {('ts_code', 'trade_date')},
            },
        ),
    ]
